### ISSUE TITLE
Update repo README.md 

### ISSUE THREAD

**Issue by SarthakSKumar** [satyamksharma/Sublit-Programs#1]
Update Repository Readme
As a part of maintaining and improving the repository, I propose updating the README.md file with the newly added readme. This new readme includes the following updates:

Table of Contents added with links to each section
Detailed information about each semester with a table of programs
Information about contribution and contact
GitHub cards with License, Issues and Stargazers count
By updating the README.md file, it will help new users to easily understand the repository structure and its contents. Additionally, it will make the repository look professional and well-maintained.

**Comment by satyamksharma** [comment]
Yeah sure @SarthakSKumar you can work on this issue
