### ISSUE TITLE
Add MIT License to the repo. 

### ISSUE THREAD

**Issue by SarthakSKumar** [satyamksharma/Sublit-Programs#3]
Add MIT License
I propose adding the MIT License to this repository to provide clear terms and conditions for the usage and distribution of the code.

The MIT License is a popular open-source license that allows for the use, modification, and distribution of software, while also protecting the contributors from liability.

To add the MIT License, the following steps can be followed:

Create a file named LICENSE in the root of the repository
Copy and paste the MIT License text into the LICENSE file
Update the README.md file with a link to the LICENSE file and add a GitHub card for the license
By adding the MIT License, we ensure that the code in this repository is used in accordance with legal regulations and provides a clear understanding of the terms and conditions of usage to users.

**Comment by satyamksharma** [comment]
Sure @SarthakSKumar go ahead.
